export const roomTypes = [
  'Living Room',
  'Living / Dining Room',
  'Dining Room',
  'Kitchen',
  'Entry',
  'Toilet',
  'Laundry',
  'Carpet floor', // This seems like an option, but following the user's list.
  'Bedroom',
  'Bathroom',
  'Masterbedroom',
  'Ensuite',
  'Hallway',
  'Single Internal Garage',
  'Double Internal Garage',
  'General Features',
] as const;

export type RoomType = (typeof roomTypes)[number];

export const roomOptionsConfig: Record<RoomType, string[]> = {
  'Living Room': [
    'Tiled floor',
    'Carpet floor',
    'Timber floor',
    'Simulated timber floor',
    'Ranch slider',
    'Air conditioning unit',
  ],
  'Living / Dining Room': [
    'Tiled floor',
    'Carpet floor',
    'Timber floor',
    'Simulated timber floor',
    'Ranch slider',
    'Air conditioning unit',
  ],
  'Dining Room': [
    'Tiled floor',
    'Carpet floor',
    'Timber floor',
    'Simulated timber floor',
    'Ranch slider',
    'Air conditioning unit',
  ],
  Kitchen: [
    'Stone benchtop',
    'Timber benchtop',
    'Laminate benchtop',
    'Island bench',
    'Breakfast bar',
    'Stainless steel sink',
    'Dual stainless steel sinks',
    'Waste disposal',
    'Gas rings stove',
    'Electric cooktop',
    'Underbench oven',
    'Wall oven',
    'Dual wall ovens',
    'Dishwasher',
    'Dual dishwasher',
    'Glass splashback',
    'Tile splashback',
    'Tiled floor',
    'Carpet floor',
    'Timber floor',
    'Vinyl floor',
    'Pantry and cupboards',
    'Box window',
    'Skylight',
    'Range hood',
  ],
  Entry: [
    'Tiled floor',
    'Carpet floor',
    'Timber floor',
    'Vinyl floor',
    'Simulated timber floor',
    'Storage cupboard',
    'Storage cupboards',
    'Skylight',
  ],
  Toilet: [
    'Toilet',
    'Handbasin',
    'Extractor fan',
    'Tiled floor',
    'Timber floor',
    'Tiled wall',
    'Partial tiled wall',
    'Vinyl floor',
  ],
  Laundry: [
    'Tiled floor',
    'Timber floor',
    'Tiled wall',
    'Partial tiled wall',
    'Vinyl floor',
    'Stainless steel tub',
    'Glass splashback',
    'Tile splashback',
    'Extractor fan',
    'Stone benchtop',
    'Timber benchtop',
    'Laminate benchtop',
    'Storage cupboard',
    'Storage cupboard with hot water cylinder',
  ],
  'Carpet floor': [ // Assuming this is a room type as per user request
    'Timber floor',
    'Single wardrobe',
    'Double wardrobe',
    'Air conditioning unit',
    'Ranch Slider',
    'Storage cupboard',
  ],
  Bedroom: [
    'Carpet floor',
    'Timber floor',
    'Single wardrobe',
    'Double wardrobe',
    'Walk-in wardrobe',
    'Ranch Slider',
    'Ensuite',
    'Air conditioning unit',
    'Double single wardrobes',
    'Full width wardrobes',
  ],
  Bathroom: [
    'Vanity unit',
    'Shower',
    'Tiled shower',
    'Toilet',
    'Built-in bath',
    'Shower over bath',
    'Dual vanity units',
    'Heated towel rail',
    'Wall mirror',
    'Heat lamp and extractor fan',
    'Extractor fan',
    'Electric heater',
    'Tiled floor',
    'Tiled wall',
    'Partial tiled wall',
    'Underfloor heating',
    'Medicine cabinet',
    'Skylight',
  ],
  Masterbedroom: [
    'Carpet floor',
    'Timber floor',
    'Single wardrobe',
    'Double wardrobe',
    'Walk-in wardrobe',
    'Ranch Slider',
    'Ensuite',
    'Air conditioning unit',
    'Double single wardrobes',
    'Full width wardrobes',
  ],
  Ensuite: [
    'Vanity unit',
    'Shower',
    'Tiled shower',
    'Toilet',
    'Built-in bath',
    'Shower over bath',
    'Dual vanity units',
    'Heated towel rail',
    'Wall mirror',
    'Heat lamp and extractor fan',
    'Extractor fan',
    'Electric heater',
    'Tiled floor',
    'Tiled wall',
    'Partial tiled wall',
    'Underfloor heating',
    'Medicine cabinet',
    'Skylight',
  ],
  Hallway: [
    'Tiled floor',
    'Carpet floor',
    'Timber floor',
    'Simulated timber floor',
    'Storage cupboard',
    'Storage cupboard with hot water cylinder',
  ],
  'Single Internal Garage': [
    'Auto door opener',
    'Single roller door',
    'Singer section door',
    'Single tilt door',
    'Carpet floor',
    'Concrete floor',
    'External access',
    'Ranch slider',
    'Laundry facilities',
  ],
  'Double Internal Garage': [
    'Auto door opener',
    'Double roller door',
    'Double section door',
    'Single tilt door',
    'Carpet floor',
    'Concrete floor',
    'External access',
    'Ranch slider',
    'Laundry facilities',
  ],
  'General Features': [
    'Security System',
    'HVAC system',
    'Ventilation System',
    'Built-in sound system',
    'Built -in vacuum system',
  ],
};
